### ISSUE TITLE
Test errors

### ISSUE THREAD

**Issue by morgalis** [tournz/binance-grid-bot#1]
Due to missing some settings information , i cant get the bot running
First issue was the dotenv file structure missing but i hardcoded the API keys in the script

When asking base and quote currency it also gives an error
my input was USDT as base and ADA as quote currency.

Any help is welcome
Greetz from belgium

**Comment by tournz** [comment]
Hi, thanks for your message. I just wrote a ReadMe file.
I stored the 2 API keys in the /etc/environment file.
I must have made a mistake in assuming that all currency codes are only 3 characters (which is why there is an error with USDT). Will check out binance's currency list.
The area that requires the most adjustments is the grid's rebalancing. It seems some executed orders go undetected and are not replaced, leading to the grid loosing orders over time.

**Comment by tournz** [comment]
Hi @morgalis, I have solved the issue. You can now launch the bot with any currency pair recognized by Binance.
